# Form implementation generated from reading ui file 'ThemNhaCungCap.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controller.DơnHangController import DonhangController

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(627, 429)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(120, 20, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(40, 0, 71, 61))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 621, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.txtID = QtWidgets.QTextEdit(parent=Dialog)
        self.txtID.setGeometry(QtCore.QRect(230, 90, 191, 31))
        self.txtID.setObjectName("txtID")
        self.txtIDDonhang = QtWidgets.QTextEdit(parent=Dialog)
        self.txtIDDonhang.setGeometry(QtCore.QRect(230, 150, 191, 31))
        self.txtIDDonhang.setObjectName("txtIDDonhang")
        self.txtIDsanpham = QtWidgets.QTextEdit(parent=Dialog)
        self.txtIDsanpham.setGeometry(QtCore.QRect(230, 210, 191, 31))
        self.txtIDsanpham.setObjectName("txtIDsanpham")
        self.iconTaiKhoan = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan.setGeometry(QtCore.QRect(50, 100, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan.setFont(font)
        self.iconTaiKhoan.setObjectName("iconTaiKhoan")
        self.iconMatKhau = QtWidgets.QLabel(parent=Dialog)
        self.iconMatKhau.setGeometry(QtCore.QRect(180, 189, 21, 21))
        self.iconMatKhau.setText("")
        self.iconMatKhau.setObjectName("iconMatKhau")
        self.iconRole = QtWidgets.QLabel(parent=Dialog)
        self.iconRole.setGeometry(QtCore.QRect(180, 250, 21, 20))
        self.iconRole.setText("")
        self.iconRole.setObjectName("iconRole")
        self.btnUpdate = QtWidgets.QPushButton(parent=Dialog)
        self.btnUpdate.setGeometry(QtCore.QRect(230, 370, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(510, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnQuayVe.setFont(font)
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.iconTaiKhoan_2 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_2.setGeometry(QtCore.QRect(50, 160, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_2.setFont(font)
        self.iconTaiKhoan_2.setObjectName("iconTaiKhoan_2")
        self.iconTaiKhoan_3 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_3.setGeometry(QtCore.QRect(50, 220, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_3.setFont(font)
        self.iconTaiKhoan_3.setObjectName("iconTaiKhoan_3")
        self.iconTaiKhoan_4 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_4.setGeometry(QtCore.QRect(50, 280, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_4.setFont(font)
        self.iconTaiKhoan_4.setObjectName("iconTaiKhoan_4")
        self.iconTaiKhoan_5 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_5.setGeometry(QtCore.QRect(50, 340, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_5.setFont(font)
        self.iconTaiKhoan_5.setObjectName("iconTaiKhoan_5")
        self.txtSoluong = QtWidgets.QTextEdit(parent=Dialog)
        self.txtSoluong.setGeometry(QtCore.QRect(230, 270, 191, 31))
        self.txtSoluong.setObjectName("txtSoluong")
        self.txtDongia = QtWidgets.QTextEdit(parent=Dialog)
        self.txtDongia.setGeometry(QtCore.QRect(230, 330, 191, 31))
        self.txtDongia.setObjectName("txtDongia")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.btnQuayVe.clicked.connect(Dialog.close)
        self.btnUpdate.clicked.connect(self.update)

    def close(self):
        self.close()

    def update(self):
        # Step 1: Collect and validate input data
        try:
            id = int(self.txtID.toPlainText().strip())
            iddonhang = int(self.txtIDDonhang.toPlainText().strip())
            idsanpham = int(self.txtIDsanpham.toPlainText().strip())
            soluong = int(self.txtSoluong.toPlainText().strip())
            dongia = float(self.txtDongia.toPlainText().strip())
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Input Error", "Please enter valid numeric values.")
            return

        # Step 2: Call the DonhangController's update method with validated and converted data
        try:
            controller = DonhangController()
            controller.updateChiTietDonHang(iddonhang, idsanpham, soluong, dongia,id)
            controller.updateTongtiendonhang(iddonhang)
            QtWidgets.QMessageBox.information(None, "Success", "Update successful.")

        except Exception as e:
            QtWidgets.QMessageBox.warning(None, "Update Error", f"An error occurred: {str(e)}")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Cập nhật Chi Tiết Đơn hàng"))
        self.iconTaiKhoan.setText(_translate("Dialog", "ID"))
        self.btnUpdate.setText(_translate("Dialog", "Cập nhật"))
        self.btnQuayVe.setText(_translate("Dialog", "Quay Về"))
        self.iconTaiKhoan_2.setText(_translate("Dialog", "IDĐơn Hàng"))
        self.iconTaiKhoan_3.setText(_translate("Dialog", "ID Sản Phẩm"))
        self.iconTaiKhoan_4.setText(_translate("Dialog", "Số Lượng"))
        self.iconTaiKhoan_5.setText(_translate("Dialog", "Đơn Giá"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
