# Form implementation generated from reading ui file 'ChiTietThongTinNhanVien.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QHeaderView
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from PyQt6.QtGui import QStandardItemModel, QStandardItem
from PyQt6.QtWidgets import QMessageBox
from Controller.TaiKhoanController import TaiKhoanController
from Dao.TaiKhoanDao import TaiKhoanDao


class Ui_Dialog(object):
    def __init__(self, main_window):
        self.main_window = main_window
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(627, 485)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(200, 10, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(40, 0, 71, 61))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 621, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 210, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(60, 270, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(60, 330, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(60, 390, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txtID = QtWidgets.QTextEdit(parent=Dialog)
        self.txtID.setGeometry(QtCore.QRect(190, 90, 181, 31))
        self.txtID.setObjectName("txtID")
        self.txtID.setReadOnly(True)
        self.txtHoVaTen = QtWidgets.QTextEdit(parent=Dialog)
        self.txtHoVaTen.setGeometry(QtCore.QRect(190, 150, 181, 31))
        self.txtHoVaTen.setObjectName("txtHoVaTen")
        self.txtTuoi = QtWidgets.QTextEdit(parent=Dialog)
        self.txtTuoi.setGeometry(QtCore.QRect(190, 210, 181, 31))
        self.txtTuoi.setObjectName("txtTuoi")
        self.txtEmail = QtWidgets.QTextEdit(parent=Dialog)
        self.txtEmail.setGeometry(QtCore.QRect(190, 270, 181, 31))
        self.txtEmail.setObjectName("txtEmail")
        self.txtDiaChi = QtWidgets.QTextEdit(parent=Dialog)
        self.txtDiaChi.setGeometry(QtCore.QRect(190, 330, 181, 31))
        self.txtDiaChi.setObjectName("txtDiaChi")
        self.txtSoDienThoai = QtWidgets.QTextEdit(parent=Dialog)
        self.txtSoDienThoai.setGeometry(QtCore.QRect(190, 390, 181, 31))
        self.txtSoDienThoai.setObjectName("txtSoDienThoai")
        self.btnSuaThongTin = QtWidgets.QPushButton(parent=Dialog)
        self.btnSuaThongTin.setGeometry(QtCore.QRect(430, 220, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnSuaThongTin.setFont(font)
        self.btnSuaThongTin.setObjectName("btnSuaThongTin")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 440, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
#===============================================================================
        #CSS label
        self.label.setStyleSheet("""
                    color: #FF4500;
                    font-weight: bold;
                """)
        #CSS Favicon
        pixamp = QPixmap("../Access/Icon/favicon.jpg")
        self.Favicon.setPixmap(pixamp)
        self.Favicon.setScaledContents(True)

        #CSS textEdit
        self.txtID.setStyleSheet("""
                                              background-color: white;
                                              color: black;
                                        """)
        self.txtEmail.setStyleSheet("""
                                              background-color: white;
                                              color: black;
                                        """)
        self.txtHoVaTen.setStyleSheet("""
                                              background-color: white;
                                              color: black;
                                        """)
        self.txtTuoi.setStyleSheet("""
                                              background-color: white;
                                              color: black;
                                        """)
        self.txtDiaChi.setStyleSheet("""
                                              background-color: white;
                                              color: black;
                                        """)
        self.txtSoDienThoai.setStyleSheet("""
                                              background-color: white;
                                              color: black;
                                        """)

        #ICon button
        self.btnSuaThongTin.setIcon(QIcon("../Access/Icon/update.png"))
        self.btnSuaThongTin.setIconSize(QSize(30, 30))
        self.pushButton_2.setIcon(QIcon("../Access/Icon/Quayve.png"))
        self.pushButton_2.setIconSize(QSize(30, 30))
        #CSS button
        self.pushButton_2.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 20px;
                                              
                                        """)
        self.btnSuaThongTin.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 10px;
                                              
                                        """)
#===============================Sự Kiện=========================================
        self.Dialog = Dialog
        self.pushButton_2.clicked.connect(self.quayve)
        self.btnSuaThongTin.clicked.connect(self.suaThongTin)

#===============================Phương Thức=====================================
    def quayve(self):
        from QuanLyTaiKhoan import Ui_Dialog as Ui_Dialog_TaiKhoan
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_TaiKhoan(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.Dialog.hide()

    def suaThongTin(self):
        id = self.txtID.toPlainText()
        hoVaTen = self.txtHoVaTen.toPlainText()
        tuoi = self.txtTuoi.toPlainText()
        email = self.txtEmail.toPlainText()
        diaChi = self.txtDiaChi.toPlainText()
        soDienThoai = self.txtSoDienThoai.toPlainText()
        controller = TaiKhoanController()
        controller.updateThongTin(id, hoVaTen, tuoi, email, diaChi, soDienThoai)
        # dao = TaiKhoanDao()
        # dao.updateThongTin(id, hoVaTen, tuoi, email, diaChi, soDienThoai)
        QMessageBox.information(self.Dialog, "Thông báo", "Sửa thông tin thành công")
        self.quayve()






#==============================================================================
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Thông Tin Nhân Viên"))
        self.label_2.setText(_translate("Dialog", "ID_USER"))
        self.label_3.setText(_translate("Dialog", "Họ Và Tên"))
        self.label_4.setText(_translate("Dialog", "Tuổi"))
        self.label_5.setText(_translate("Dialog", "Email"))
        self.label_6.setText(_translate("Dialog", "Địa chỉ"))
        self.label_7.setText(_translate("Dialog", "Số Điện Thoại"))
        self.btnSuaThongTin.setText(_translate("Dialog", "Sửa Thông Tin"))
        self.pushButton_2.setText(_translate("Dialog", "Quay Về"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
