# Form implementation generated from reading ui file 'QuanLyTaiKhoan.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from Controller.DơnHangController import DonhangController
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(903, 672)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(260, 10, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.tblDuLieu = QtWidgets.QTableView(parent=Dialog)
        self.tblDuLieu.setGeometry(QtCore.QRect(0, 380, 911, 321))
        self.tblDuLieu.setStyleSheet("background-color:white;\n"
"color:black;")
        self.tblDuLieu.setObjectName("tblDuLieu")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 911, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(850, 0, 61, 51))
        self.btnQuayVe.setStyleSheet("")
        self.btnQuayVe.setText("")
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.txtiddonhang = QtWidgets.QTextEdit(parent=Dialog)
        self.txtiddonhang.setGeometry(QtCore.QRect(150, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.txtiddonhang.setFont(font)
        self.txtiddonhang.setObjectName("txtiddonhang")
        self.btnThem = QtWidgets.QPushButton(parent=Dialog)
        self.btnThem.setGeometry(QtCore.QRect(610, 300, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnThem.setFont(font)
        self.btnThem.setAcceptDrops(False)
        self.btnThem.setFlat(False)
        self.btnThem.setObjectName("btnThem")
        self.soluong = QtWidgets.QTextEdit(parent=Dialog)
        self.soluong.setGeometry(QtCore.QRect(500, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.soluong.setFont(font)
        self.soluong.setObjectName("soluong")
        self.idsanpham = QtWidgets.QTextEdit(parent=Dialog)
        self.idsanpham.setGeometry(QtCore.QRect(150, 230, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.idsanpham.setFont(font)
        self.idsanpham.setObjectName("idsanpham")
        self.dongia = QtWidgets.QTextEdit(parent=Dialog)
        self.dongia.setGeometry(QtCore.QRect(500, 230, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.dongia.setFont(font)
        self.dongia.setObjectName("dongia")
        self.btnSua = QtWidgets.QPushButton(parent=Dialog)
        self.btnSua.setGeometry(QtCore.QRect(320, 300, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnSua.setFont(font)
        self.btnSua.setAcceptDrops(False)
        self.btnSua.setFlat(False)
        self.btnSua.setObjectName("btnSua")
        self.btnXoa = QtWidgets.QPushButton(parent=Dialog)
        self.btnXoa.setGeometry(QtCore.QRect(50, 300, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnXoa.setFont(font)
        self.btnXoa.setAcceptDrops(False)
        self.btnXoa.setFlat(False)
        self.btnXoa.setObjectName("btnXoa")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(27, 250, 121, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(387, 140, 91, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(387, 240, 91, 20))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.btnThem.clicked.connect(self.addChiTietDonHang)
        self.btnSua.clicked.connect(self.updateChiTietDonHang)
        self.btnXoa.clicked.connect(self.deleteChiTietDonHang)
        self.tblDuLieu.doubleClicked.connect(self.load)
        self.btnQuayVe.clicked.connect(Dialog.close)
        self.load_data()


    def close(self):
        self.close()
    def load_data(self):
        controller = DonhangController()
        data = controller.getAllChitietdonhang()
        model = QtGui.QStandardItemModel(len(data), 7)
        model.setHorizontalHeaderLabels(["id","Id Đơn Hàng", "Id Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền", "Ngày bán"])
        for row, item in enumerate(data):
            model.setItem(row, 0, QtGui.QStandardItem(str(item[0])))
            model.setItem(row, 1, QtGui.QStandardItem(str(item[1])))
            model.setItem(row, 2, QtGui.QStandardItem(str(item[2])))
            model.setItem(row, 3, QtGui.QStandardItem(str(item[3])))
            model.setItem(row, 4, QtGui.QStandardItem(str(item[4])))
            model.setItem(row, 5, QtGui.QStandardItem(str(item[5])))
            model.setItem(row, 6, QtGui.QStandardItem(str(item[6])))
        self.tblDuLieu.setModel(model)

    def addChiTietDonHang(self):
        if self.txtiddonhang.toPlainText() == "" or self.idsanpham.toPlainText() == "" or self.soluong.toPlainText() == "" or self.dongia.toPlainText() == "":
            QtWidgets.QMessageBox.warning(None, "Lỗi", "Vui lòng nhập đầy đủ thông tin")
            return
        else:
            iddonhang = int(self.txtiddonhang.toPlainText())
            idsanpham = int(self.idsanpham.toPlainText())
            soluong = int(self.soluong.toPlainText())
            dongia = int(self.dongia.toPlainText())
            controller = DonhangController()
            controller.addChiTietDonHang(iddonhang,idsanpham, soluong, dongia)
            controller.updateTongtiendonhang(iddonhang)
            self.load_data()

    def updateChiTietDonHang(self):
        row = self.tblDuLieu.currentIndex().row()
        if row == -1:
            QtWidgets.QMessageBox.warning(None, "Lỗi", "Vui lòng chọn dòng cần cập nhật")
            return

        # Assuming the first column is ID, second is ID Đơn Hàng, etc.
        id = self.tblDuLieu.model().data(self.tblDuLieu.model().index(row, 0))
        idDonHang = self.tblDuLieu.model().data(self.tblDuLieu.model().index(row, 1))
        idSanPham = self.tblDuLieu.model().data(self.tblDuLieu.model().index(row, 2))
        soLuong = self.tblDuLieu.model().data(self.tblDuLieu.model().index(row, 3))
        donGia = self.tblDuLieu.model().data(self.tblDuLieu.model().index(row, 4))

        from Capnhatchitietdonhang import Ui_Dialog as capnhat
        self.dialog = QtWidgets.QDialog()
        self.ui = capnhat()
        self.ui.setupUi(self.dialog)

        # Set the retrieved data to the dialog's fields
        self.ui.txtID.setText(str(id))
        self.ui.txtIDDonhang.setText(str(idDonHang))
        self.ui.txtIDsanpham.setText(str(idSanPham))
        self.ui.txtSoluong.setText(str(soLuong))
        self.ui.txtDongia.setText(str(donGia))

        self.dialog.show()

    def load(self):
        self.load_data()

    # def load(self):
    #     row = self.tblDuLieu.currentIndex().row()
    #
    #     iddonhang = self.tblDuLieu.model().index(row, 1)
    #     idsanpham = self.tblDuLieu.model().index(row, 2)
    #     soluong = self.tblDuLieu.model().index(row, 3)
    #     dongia = self.tblDuLieu.model().index(row, 4)
    #     self.txtiddonhang.setPlainText(str(self.tblDuLieu.model().data(iddonhang)))
    #     self.idsanpham.setPlainText(str(self.tblDuLieu.model().data(idsanpham)))
    #     self.soluong.setPlainText(str(self.tblDuLieu.model().data(soluong)))
    #     self.dongia.setPlainText(str(self.tblDuLieu.model().data(dongia)))
    def deleteChiTietDonHang(self):
        row = self.tblDuLieu.currentIndex().row()
        if row == -1:
            QtWidgets.QMessageBox.warning(None, "Lỗi", "Vui lòng chọn dòng cần xoá")
            return
        else:
            item = self.tblDuLieu.model().index(row, 0)
            idsanpham = self.tblDuLieu.model().index(row, 2)
            soluong = self.tblDuLieu.model().index(row, 3)
            if item is not None:
                id = self.tblDuLieu.model().data(item)
                idsanpham = self.tblDuLieu.model().data(idsanpham)
                soluong = self.tblDuLieu.model().data(soluong)
                controller = DonhangController()
                controller.deleteChitietDonhang(id,idsanpham, soluong)
            self.load_data()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Chi Tiết Đơn Hàng"))
        self.txtiddonhang.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnThem.setText(_translate("Dialog", "Thêm"))
        self.soluong.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.idsanpham.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dongia.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnSua.setText(_translate("Dialog", "Sửa"))
        self.btnXoa.setText(_translate("Dialog", "Xoá"))
        self.label_2.setText(_translate("Dialog", "Id Đơn Hàng"))
        self.label_3.setText(_translate("Dialog", "Id Sản Phẩm"))
        self.label_4.setText(_translate("Dialog", "Số Lượng"))
        self.label_5.setText(_translate("Dialog", "Đơn Giá"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
