# Form implementation generated from reading ui file 'ChucNangKhac.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QHeaderView
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from PyQt6.QtGui import QStandardItemModel, QStandardItem
from PyQt6.QtWidgets import QMessageBox

class Ui_Dialog(object):
    def __init__(self, main_window):
        self.main_window = main_window
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(844, 351)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(280, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(40, 0, 71, 61))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 841, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 90, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 90, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 240, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 240, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(780, 0, 61, 61))
        self.btnQuayVe.setText("")
        self.btnQuayVe.setObjectName("btnQuayVe")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        #===============================================================================
        #CSS Label
        self.label.setStyleSheet("""
                    color: #FF4500;
                    font-weight: bold;
                """)

        #CSS Favicon
        pixamp = QPixmap("../Access/Icon/favicon.jpg")
        self.Favicon.setPixmap(pixamp)
        self.Favicon.setScaledContents(True)


        #CSS icon button
        self.pushButton_2.setIcon(QIcon("../Access/Icon/updatechitietsanpham.png"))
        self.pushButton_2.setIconSize(QSize(40, 40))
        self.pushButton_4.setIcon(QIcon("../Access/Icon/updateuser.png"))
        self.pushButton_4.setIconSize(QSize(40, 40))
        self.pushButton_3.setIcon(QIcon("../Access/Icon/maintenance.png"))
        self.pushButton_3.setIconSize(QSize(40, 40))
        self.pushButton_5.setIcon(QIcon("../Access/Icon/warehouse (1).png"))
        self.pushButton_5.setIconSize(QSize(40, 40))
        self.btnQuayVe.setIcon(QIcon("../Access/Icon/Quayve.png"))
        self.btnQuayVe.setIconSize(QSize(40, 40))

        #CSS BUTTON
        self.pushButton_2.setStyleSheet("""
                                            background-color:#FFFF00;
                                            border-radius: 20px;
                                            border: 2px solid #00FF00;
                                    """)
        self.pushButton_4.setStyleSheet("""
                                            background-color:#FFFF00;
                                            border-radius: 20px;
                                            border: 2px solid #00FF00;
                                    """)
        self.pushButton_5.setStyleSheet("""
                                            background-color:#FFFF00;
                                            border-radius: 20px;
                                            border: 2px solid #00FF00;
                                    """)
        self.pushButton_3.setStyleSheet("""
                                            background-color:#FFFF00;
                                            border-radius: 20px;
                                            border: 2px solid #00FF00;
                                    """)
        self.btnQuayVe.setStyleSheet("""
                                            background-color:#FFFF00;
                                            border-radius: 20px;
                                            border: 2px solid #00FF00;
                                    """)
#===============================================================================
        self.Dialog = Dialog
        self.btnQuayVe.clicked.connect(self.quayve)
        self.pushButton_5.clicked.connect(self.quanlykho)
        self.pushButton_3.clicked.connect(self.baotri)
        self.pushButton_4.clicked.connect(self.openThemChiTietNhanVien)
        self.pushButton_2.clicked.connect(self.openThemChiTietSanPham)

#===============================================================================
    def quayve(self):
        from View.UiAdmin import Ui_MainWindow
        self.main_window = QtWidgets.QMainWindow()  # tạo một instance mới của QMainWindow
        self.ui = Ui_MainWindow(self.main_window)  # truyền self.main_window như là MainWindow
        self.ui.setupUi(self.main_window)
        self.main_window.show()
        self.Dialog.hide()

    def quanlykho(self):
        QMessageBox.information(self.Dialog, "Thông báo",
                                "Chức năng đang được Bảo Trì!")

    def baotri(self):
        QMessageBox.information(self.Dialog, "Thông báo",
                                "Chức năng đang được phát triển!")

    def openThemChiTietSanPham(self):
        from View.ThemChiTietSanPham import Ui_Dialog as Ui_Dialog_ThemChiTietSanPham
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_ThemChiTietSanPham(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.Dialog.hide()

    def openThemChiTietNhanVien(self):
        from ThemThongTinNhanVien import Ui_Dialog as Ui_Dialog_ThemThongTinNhanVien
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_ThemThongTinNhanVien(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.Dialog.hide()
    #===============================================================================
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "CHỨC NĂNG KHÁC"))
        self.pushButton_2.setText(_translate("Dialog", "Thêm Chi Tiết Sản Phẩm"))
        self.pushButton_4.setText(_translate("Dialog", "Thêm Thông Tin Nhân Viên"))
        self.pushButton_3.setText(_translate("Dialog", "Bảo Trì"))
        self.pushButton_5.setText(_translate("Dialog", "Quản Lý Kho Hàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
