# Form implementation generated from reading ui file '.\LoginUser.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtGui import QPixmap
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from Controller.LoginController import LoginController

import dialog_manager

class Ui_Dialog(object):
    def __init__(self, main_window):
        self.main_window = main_window
    def setupUi(self, Dialog):
        # Ẩn thanh hiện thông báo DiaLog
        Dialog.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Dialog.setObjectName("Dialog")
        Dialog.resize(552, 367)
        Dialog.setStyleSheet("background: #E0FFFF;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(160, 60, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.iconAccount = QtWidgets.QLabel(parent=Dialog)
        self.iconAccount.setGeometry(QtCore.QRect(130, 150, 21, 21))
        self.iconAccount.setObjectName("iconAccount")
        self.txtTaiKhoan = QtWidgets.QLineEdit(parent=Dialog)
        self.txtTaiKhoan.setGeometry(QtCore.QRect(160, 140, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.txtTaiKhoan.setFont(font)
        self.txtTaiKhoan.setObjectName("txtTaiKhoan")
        self.btnDangNhap = QtWidgets.QPushButton(parent=Dialog)
        self.btnDangNhap.setGeometry(QtCore.QRect(200, 280, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDangNhap.setFont(font)
        self.btnDangNhap.setStyleSheet("")
        self.btnDangNhap.setObjectName("btnDangNhap")
        self.iconAccount_2 = QtWidgets.QLabel(parent=Dialog)
        self.iconAccount_2.setGeometry(QtCore.QRect(130, 220, 21, 21))
        self.iconAccount_2.setObjectName("iconAccount_2")
        # thay đổi từ QLineEdit sang QTextEdit
        self.txtMatKhau = QtWidgets.QLineEdit(parent=Dialog)
        self.txtMatKhau.setGeometry(QtCore.QRect(160, 210, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.txtMatKhau.setFont(font)
        self.txtMatKhau.setObjectName("txtMatKhau")
        # đổi mật khẩu thannh dạng *
        self.txtMatKhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(490, 320, 61, 51))
        self.btnQuayVe.setText("")
        self.btnQuayVe.setObjectName("btnQuayVe")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        #============================CSS===================================
        #CSS Label
        self.label.setStyleSheet("""
            color: #FF4500;
            font-weight: bold;
        """)

        # CSS hai hình
        pixmapAccount = QPixmap("../Access/Icon/user-solid.svg")
        self.iconAccount.setPixmap(pixmapAccount)
        self.iconAccount.setScaledContents(True)

        pixmapPassword = QPixmap("../Access/Icon/password-solid.svg")
        self.iconAccount_2.setPixmap(pixmapPassword)
        self.iconAccount_2.setScaledContents(True)

        self.btnQuayVe.setIcon(QIcon("../Access/Icon/Quayve.png"))
        self.btnQuayVe.setIconSize(QSize(40, 40))

        self.btnQuayVe.setStyleSheet("""
                                        background-color:#FFFF00;
                                        border-radius: 10px;
                                        border: 2px solid #00FF00;
                                      """)

        #CSS Vùng Nhập Liệu
        self.txtTaiKhoan.setStyleSheet("""
                background: white;
                border: 3px solid black;
                border-radius: 10px;  
            """)
        self.txtTaiKhoan.setPlaceholderText("Tài Khoản") #Tạo chữ giả

        self.txtMatKhau.setStyleSheet("""
                background: white;
                border: 3px solid black;
                border-radius: 10px;  
            """)
        self.txtMatKhau.setPlaceholderText("Mật Khẩu") #Tạo chữ giả

        #CSS Button
        self.btnDangNhap.setStyleSheet("""
                background-color: #000080;
                color: #FFFFFF;
                font-weight: bold;
                border-radius: 10px;
            """)

#============================Event==============================================
        self.Dialog = Dialog
        self.btnQuayVe.clicked.connect(lambda: dialog_manager.openLogin(self.Dialog))
        self.btnDangNhap.clicked.connect(self.openlogin)
        # Thiết lập thứ tự chuyển tiếp
        Dialog.setTabOrder(self.txtTaiKhoan, self.txtMatKhau)
#============================Function===========================================
    def openlogin(self):
        from UiUser import Ui_MainWindow as Ui_MainWindow_User
        from UiManager import Ui_MainWindow as Ui_MainWindow_QuanLy
        self.login_controller = LoginController()
        username = self.txtTaiKhoan.text()
        password = self.txtMatKhau.text()
        print(f"Username: {username}, Password: {password}")
        user = self.login_controller.get_user(username)
        print(f"User: {user}")  # Debug line
        if user is None or user[1] != password:
            QtWidgets.QMessageBox.warning(self.Dialog, "Lỗi",
                                          "Tài khoản hoặc mật khẩu không chính xác")
        elif user[2] == 3:
            QtWidgets.QMessageBox.information(self.Dialog, "Thành công",
                                              "Đăng nhập thành công \n"
                                              "Xin Chào Nhân Viên ")

            self.admin_window = QtWidgets.QMainWindow()  # Create a new window for the admin UI
            self.admin_ui = Ui_MainWindow_User(self.admin_window)  # Create a new instance of Ui_Admin
            self.admin_ui.setupUi(self.admin_window)  # Setup the admin UI
            self.admin_window.show()  # Show the admin window
            self.Dialog.hide()  # Hide the login window
        elif user[2] == 2:
            QtWidgets.QMessageBox.information(self.Dialog, "Thành công",
                                              "Đăng nhập thành công \n"
                                              "Xin Chào Quản Lý")
            self.quanly_window = QtWidgets.QMainWindow()  # Create a new window for the QuanLy UI
            self.quanly_ui = Ui_MainWindow_QuanLy(self.quanly_window)  # Create a new instance of Ui_QuanLy
            self.quanly_ui.setupUi(self.quanly_window)  # Setup the QuanLy UI
            self.quanly_window.show()  # Show the QuanLy window
            self.Dialog.hide()  # Hide the login window
        else:
            QtWidgets.QMessageBox.warning(self.Dialog, "Lỗi",
                                          "Bạn không có quyền truy cập")

    #===================================================================
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Đăng Nhập USER"))
        self.iconAccount.setText(_translate("Dialog", "d"))
        self.btnDangNhap.setText(_translate("Dialog", "Đăng Nhập"))
        self.iconAccount_2.setText(_translate("Dialog", "d"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
