# Form implementation generated from reading ui file 'Quanlydonhanguser.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QStandardItemModel, QStandardItem
from PyQt6.QtWidgets import QHeaderView
from View.UiUser import Ui_MainWindow
from Controller.DơnHangController import DonhangController
from View.Chitietdonhang import Ui_Dialog as Ui_Chitietdonhang


class Ui_Dialog(object):
    def __init__(self, MainWindow):
        self.MainWindow = MainWindow

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(903, 672)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(260, 10, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.tblDuLieu = QtWidgets.QTableView(parent=Dialog)
        self.tblDuLieu.setGeometry(QtCore.QRect(0, 220, 911, 481))
        self.tblDuLieu.setStyleSheet("background-color:white;\n""color:black;")
        self.tblDuLieu.setObjectName("tblDuLieu")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 911, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(850, 0, 61, 51))
        self.btnQuayVe.setStyleSheet("")
        self.btnQuayVe.setText("")
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.btnTaodinhang = QtWidgets.QPushButton(parent=Dialog)
        self.btnTaodinhang.setGeometry(QtCore.QRect(360, 120, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnTaodinhang.setFont(font)
        self.btnTaodinhang.setObjectName("btnTaodinhang")
        self.txtTimKiem = QtWidgets.QTextEdit(parent=Dialog)
        self.txtTimKiem.setGeometry(QtCore.QRect(150, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.txtTimKiem.setFont(font)
        self.txtTimKiem.setObjectName("txtTimKiem")
        self.btnSuadonhang = QtWidgets.QPushButton(parent=Dialog)
        self.btnSuadonhang.setGeometry(QtCore.QRect(540, 120, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnSuadonhang.setFont(font)
        self.btnSuadonhang.setObjectName("btnSuadonhang")
        self.btnSearch = QtWidgets.QPushButton(parent=Dialog)
        self.btnSearch.setGeometry(QtCore.QRect(20, 120, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.btnTaohoadon = QtWidgets.QPushButton(parent=Dialog)
        self.btnTaohoadon.setGeometry(QtCore.QRect(730, 120, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnTaohoadon.setFont(font)
        self.btnTaohoadon.setAcceptDrops(False)
        self.btnTaohoadon.setFlat(False)
        self.btnTaohoadon.setObjectName("btnTaohoadon")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.Dialog = Dialog
        self.load_data()
        self.btnTaodinhang.clicked.connect(self.open_taodonhang)
        self.btnSearch.clicked.connect(self.search)
        self.btnTaohoadon.clicked.connect(self.chitietdonhang)
        self.tblDuLieu.doubleClicked.connect(self.open_chitietdonhang)
        self.btnQuayVe.clicked.connect(self.close)
        self.btnSuadonhang.clicked.connect(self.open_suadonhang)


    def open_suadonhang(self):
        from View.Suadonhang import Ui_Dialog as Ui_Suadonhang
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Suadonhang()
        self.ui.setupUi(self.window)
        self.window.show()

    def close(self):
        from UiManager import Ui_MainWindow
        self.main_window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(self.main_window)
        self.ui.setupUi(self.main_window)
        self.main_window.show()
        self.Dialog.hide()


    def chitietdonhang(self):
        from Chitietdonhang import Ui_Dialog as Ui_Chitietdonhang
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Chitietdonhang()
        self.ui.setupUi(self.window)
        self.window.show()




    def open_chitietdonhang(self):
        try:
            row = self.tblDuLieu.currentIndex().row()
            item = self.tblDuLieu.model().index(row, 0)

            if item is not None:
                idDonHang = self.tblDuLieu.model().data(item)
                controller = DonhangController()
                data = controller.loadctdh(idDonHang)
                if data:
                    model = QStandardItemModel()
                    model.setRowCount(len(data))
                    model.setColumnCount(7)
                    model.setHorizontalHeaderLabels(
                        ["ID", "ID Đơn Hàng", "ID Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền", "Ngày bán"])
                    for i, nv in enumerate(data):
                        for j, data in enumerate(nv):
                            model.setItem(i, j, QStandardItem(str(data)))
                    self.tblDuLieu.setModel(model)

                else:
                    QtWidgets.QMessageBox.warning(self, "Thông báo", "Không có dữ liệu")
            else:
                print("No item selected.")
        except Exception as e:
            print(f"An error occurred: {e}")


    # def open_chitietdonhang(self):
    #     row = self.tblDuLieu.currentIndex().row()
    #     item = self.tblDuLieu.model().index(row, 0)
    #
    #     if item is not None:
    #         idDonHang = self.tblDuLieu.model().data(item)
    #         try:
    #             self.window = QtWidgets.QDialog()
    #             self.ui = Ui_Chitietdonhang()
    #             self.ui.setupUi(self.window)
    #             self.window.show()
    #             controller = DonhangController()
    #             data = controller.loadctdh(idDonHang)
    #             self.tblDuLieu.setRowCount(len(data))
    #             self.tblDuLieu.setColumnCount(7)
    #             self.tblDuLieu.setHorizontalHeaderLabels(["ID", "ID Đơn Hàng", "ID Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền", "Ngày bán"])
    #             for i, nv in enumerate(data):
    #                 for j, data in enumerate(nv):
    #                     self.tblDuLieu.setItem(i, j, QtWidgets.QTableWidgetItem(str(data)))
    #         except Exception as e:
    #             print(f"An error occurred: {e}")
    #     else:
    #         print("No item selected.")
    def open_taodonhang(self):
        from View.Taodonhang import Ui_Dialog as Ui_Taodonhang
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Taodonhang()
        self.ui.setupUi(self.window)
        self.window.show()

    def search(self):
        if self.txtTimKiem.toPlainText() != "":
            model = QStandardItemModel()
            model.setHorizontalHeaderLabels(['ID_Đơn Hàng', 'IDUser', 'Tổng tiền'])
            controller = DonhangController()
            data = controller.searchByIdUser(self.txtTimKiem.toPlainText())
            for row in data:
                items = [QStandardItem(str(field)) for field in row]
                model.appendRow(items)
            self.tblDuLieu.setModel(model)
            self.tblDuLieu.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        else:
            self.load_data()

    def load_data(self):
        model = QStandardItemModel()
        model.setHorizontalHeaderLabels(['ID_Đơn Hàng', 'IDUser','Tên khách','SĐT', 'Tổng tiền'])
        controller = DonhangController()
        data = controller.getAllDonHang()
        for row in data:
            items = [QStandardItem(str(field)) for field in row]
            model.appendRow(items)
        self.tblDuLieu.setModel(model)
        self.tblDuLieu.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Quản Lý Đơn Hàng"))
        self.btnTaodinhang.setText(_translate("Dialog", "Tạo Đơn Hàng"))
        self.txtTimKiem.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnSuadonhang.setText(_translate("Dialog", "Sửa Đơn Hàng"))
        self.btnSearch.setText(_translate("Dialog", "Tìm Kiếm"))
        self.btnTaohoadon.setText(_translate("Dialog", "Chi Tiết Đơn Hàng"))






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
