# Form implementation generated from reading ui file 'QuanLySanPham.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QHeaderView
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from PyQt6.QtGui import QStandardItemModel, QStandardItem
from PyQt6.QtWidgets import QMessageBox
from Controller.SanPhamController import SanPhamController
from datetime import date
class Ui_Dialog(object):
    def __init__(self, main_window):
      self.main_window = main_window
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(911, 695)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(270, 10, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.tblDuLieu = QtWidgets.QTableView(parent=Dialog)
        self.tblDuLieu.setGeometry(QtCore.QRect(0, 100, 911, 431))
        self.tblDuLieu.setStyleSheet("background-color:white;\n"
"color:black;")
        self.tblDuLieu.setObjectName("tblDuLieu")
        (self.tblDuLieu.setSelectionBehavior
         (QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows))
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 911, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 540, 911, 16))
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.btnThemSanPham = QtWidgets.QPushButton(parent=Dialog)
        self.btnThemSanPham.setGeometry(QtCore.QRect(30, 580, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnThemSanPham.setFont(font)
        self.btnThemSanPham.setObjectName("btnThemSanPham")
        self.btnCapNhatSanPham = QtWidgets.QPushButton(parent=Dialog)
        self.btnCapNhatSanPham.setGeometry(QtCore.QRect(290, 580, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnCapNhatSanPham.setFont(font)
        self.btnCapNhatSanPham.setObjectName("btnCapNhatSanPham")
        self.btnXoaSanPham = QtWidgets.QPushButton(parent=Dialog)
        self.btnXoaSanPham.setGeometry(QtCore.QRect(550, 580, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btnXoaSanPham.setFont(font)
        self.btnXoaSanPham.setObjectName("btnXoaSanPham")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(844, 642, 61, 51))
        self.btnQuayVe.setStyleSheet("")
        self.btnQuayVe.setText("")
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(10, 10, 131, 71))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

#==================================CSS=========================================
        #CSS Label
        self.label.setStyleSheet("""
                    color: #FF4500;
                    font-weight: bold;
                """)

        #CSS Favicon
        pixamp = QPixmap("../Access/Icon/favicon.jpg")
        self.Favicon.setPixmap(pixamp)
        self.Favicon.setScaledContents(True)

        #CSS Icon Button

        self.btnThemSanPham.setIcon(QIcon("../Access/Icon/plus.png"))
        self.btnThemSanPham.setIconSize(QSize(40,40))
        self.btnXoaSanPham.setIcon(QIcon("../Access/Icon/delete.png"))
        self.btnXoaSanPham.setIconSize(QSize(40,40))
        self.btnCapNhatSanPham.setIcon(QIcon("../Access/Icon/update.png"))
        self.btnCapNhatSanPham.setIconSize(QSize(40,40))
        self.btnQuayVe.setIcon(QIcon("../Access/Icon/back.png"))
        self.btnQuayVe.setIconSize(QSize(40,40))

        #CSS Button
        self.btnThemSanPham.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 10px;
                                            """)
        self.btnCapNhatSanPham.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 10px;
                                            """)
        self.btnXoaSanPham.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 10px;
                                         """)
        self.btnQuayVe.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 25px;
                                     """)
#==================================Sự Kiện======================================
        self.Dialog = Dialog
        self.load_data()
        self.tblDuLieu.doubleClicked.connect(self.row_double_clicked)
        self.tblDuLieu.clicked.connect(self.row_clicked)
        self.btnQuayVe.clicked.connect(self.quayve)
        self.btnThemSanPham.clicked.connect(self.openthemSanPham)
        self.btnCapNhatSanPham.clicked.connect(self.capNhatSanPham)
        self.btnXoaSanPham.clicked.connect(self.xoaSanPham)
#==================================Hàm==========================================
    def load_data(self):
      model = QStandardItemModel()
      model.setHorizontalHeaderLabels(['ID_SảnPhẩm',
                                       'Số_Lượng', 'Tên_Sản_Phẩm',
                                       'Đơn_Giá', 'ID_NhàCungCấp'])
      controller = SanPhamController()
      data = controller.getAllSanPham()
      for row in data:
        items = [QStandardItem(str(field)) for field in row]
        model.appendRow(items)
      self.tblDuLieu.setModel(model)

      (self.tblDuLieu.horizontalHeader().setSectionResizeMode
       (QHeaderView.ResizeMode.Stretch))

    def quayve(self):
      from View.UiUser import Ui_MainWindow
      self.main_window = QtWidgets.QMainWindow()
      self.ui = Ui_MainWindow(self.main_window)
      self.ui.setupUi(self.main_window)
      self.main_window.show()
      self.Dialog.hide()

    def row_clicked(self, index):
      global selected_row_data
      selected_row_data = []
      for i in range(self.tblDuLieu.model().columnCount()):
        selected_row_data.append(self.tblDuLieu.model().index(index.row(), i).data())
      print("Selected row data:", selected_row_data)


    def openthemSanPham(self):
      from ThemSanPhamUser import Ui_Dialog as Ui_Dialog_ThemSanPham
      self.window = QtWidgets.QDialog()
      self.ui = Ui_Dialog_ThemSanPham(self.window)
      self.ui.setupUi(self.window)
      self.window.show()
      self.Dialog.hide()

    def xoaSanPham(self):
      selected_row_data = []
      index = self.tblDuLieu.currentIndex()
      for i in range(self.tblDuLieu.model().columnCount()):
        selected_row_data.append(self.tblDuLieu.model().index(index.row(), i).data())
      confirm = QMessageBox.question(self.Dialog, "Xác nhận", "Bạn có chắc chắn muốn xóa tài khoản này không?",
                                     QMessageBox.StandardButton.Yes |
                                     QMessageBox.StandardButton.No )
      if confirm == QMessageBox.StandardButton.Yes:
        id = selected_row_data[0]
        controller = SanPhamController()
        controller.deleteSanPham(id)
        QMessageBox.information(self.Dialog, "Thông báo", "Xóa tài khoản thành công")
        self.load_data()

    def capNhatSanPham(self):
      from CapNhatSanPhamUser import Ui_Dialog as Ui_Dialog_CapNhatSanPham
      self.window = QtWidgets.QDialog()
      self.ui = Ui_Dialog_CapNhatSanPham(self.window)
      self.ui.setupUi(self.window)
      self.window.show()
      self.Dialog.hide()
      #Truyền dữ liệu sang bên Cập Nhật Sản Phẩm
      global selected_row_data
      self.ui.idSanPham.setText(selected_row_data[0])
      self.ui.txtSoLuong.setText(selected_row_data[1])
      self.ui.txtTenSanPham.setText(selected_row_data[2])
      self.ui.txtDonGia.setText(selected_row_data[3])
      self.ui.txtNhaCungCap.setText(selected_row_data[4])


    def row_double_clicked(self, index):
      idsanpham = self.tblDuLieu.model().index(index.row(), 0).data()
      controller = SanPhamController()
      thongtin = controller.searchById(idsanpham)
      # print(thongtin)
      if not thongtin:
        QMessageBox.information(self.Dialog, "Thông báo",
                                "Không có thông tin nhân viên trên Database")
      else:
        thongtin = controller.getAllChiTietSanPham()
        # print(thongtin)
        from ChiTietSanPhamUser import Ui_Dialog as Ui_DiaLog_ChiTietSanPham
        self.window = QtWidgets.QDialog()
        self.ui = Ui_DiaLog_ChiTietSanPham(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.Dialog.hide()
        # Load dữ liệu từ QuanLySanPham.py vào các trường idSanPham,
        # txtNgayNhapKho, txtHanSuDung, txtLoai của ChiTietSanPham.py

        for info in thongtin:
          if int(info[0]) == int(idsanpham):
            self.ui.idSanPham.setText(str(info[0]))
            self.ui.txtNgayNhapKho.setText(str(info[1]))
            self.ui.txtHanSuDung.setText(str(info[2]))
            self.ui.txtLoai.setText(str(info[3]))

        global selected_row_data
        self.ui.idSanPham.setText(selected_row_data[0])
        self.ui.txtSoLuong.setText(selected_row_data[1])
        self.ui.txtTenSanPham.setText(selected_row_data[2])
        self.ui.txtNhaCungCap.setText(selected_row_data[4])



#==============================================================================
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Quản Lý Danh Sách Sản Phẩm"))
        self.btnThemSanPham.setText(_translate("Dialog", "Thêm Sản Phẩm"))
        self.btnCapNhatSanPham.setText(_translate("Dialog", "Cập Nhật Sản Phẩm"))
        self.btnXoaSanPham.setText(_translate("Dialog", "Xoá Sản Phẩm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
