# Form implementation generated from reading ui file 'SuaNhaCungCap.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QHeaderView
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from PyQt6.QtWidgets import QMessageBox

from Controller.NhaCungCapController import NhaCungCapController


class Ui_Dialog(object):
    def __init__(self, main_window):
        self.main_window = main_window
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(627, 429)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(220, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(40, 0, 71, 61))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 621, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.txtTaiKhoan = QtWidgets.QTextEdit(parent=Dialog)
        self.txtTaiKhoan.setGeometry(QtCore.QRect(230, 90, 191, 31))
        self.txtTaiKhoan.setObjectName("txtTaiKhoan")
        self.txtTaiKhoan.setReadOnly(True)
        self.txtMatKhau = QtWidgets.QTextEdit(parent=Dialog)
        self.txtMatKhau.setGeometry(QtCore.QRect(230, 150, 191, 31))
        self.txtMatKhau.setObjectName("txtMatKhau")
        self.txtDiaChi = QtWidgets.QTextEdit(parent=Dialog)
        self.txtDiaChi.setGeometry(QtCore.QRect(230, 210, 191, 31))
        self.txtDiaChi.setObjectName("txtDiaChi")
        self.iconTaiKhoan = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan.setGeometry(QtCore.QRect(50, 100, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan.setFont(font)
        self.iconTaiKhoan.setObjectName("iconTaiKhoan")
        self.iconMatKhau = QtWidgets.QLabel(parent=Dialog)
        self.iconMatKhau.setGeometry(QtCore.QRect(180, 189, 21, 21))
        self.iconMatKhau.setText("")
        self.iconMatKhau.setObjectName("iconMatKhau")
        self.iconRole = QtWidgets.QLabel(parent=Dialog)
        self.iconRole.setGeometry(QtCore.QRect(180, 250, 21, 20))
        self.iconRole.setText("")
        self.iconRole.setObjectName("iconRole")
        self.btnSuaNhaCungCap = QtWidgets.QPushButton(parent=Dialog)
        self.btnSuaNhaCungCap.setGeometry(QtCore.QRect(230, 370, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnSuaNhaCungCap.setFont(font)
        self.btnSuaNhaCungCap.setObjectName("btnSuaNhaCungCap")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(510, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnQuayVe.setFont(font)
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.iconTaiKhoan_2 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_2.setGeometry(QtCore.QRect(50, 160, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_2.setFont(font)
        self.iconTaiKhoan_2.setObjectName("iconTaiKhoan_2")
        self.iconTaiKhoan_3 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_3.setGeometry(QtCore.QRect(50, 220, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_3.setFont(font)
        self.iconTaiKhoan_3.setObjectName("iconTaiKhoan_3")
        self.iconTaiKhoan_4 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_4.setGeometry(QtCore.QRect(50, 280, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_4.setFont(font)
        self.iconTaiKhoan_4.setObjectName("iconTaiKhoan_4")
        self.iconTaiKhoan_5 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_5.setGeometry(QtCore.QRect(50, 340, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_5.setFont(font)
        self.iconTaiKhoan_5.setObjectName("iconTaiKhoan_5")
        self.txtSoDienThoai = QtWidgets.QTextEdit(parent=Dialog)
        self.txtSoDienThoai.setGeometry(QtCore.QRect(230, 270, 191, 31))
        self.txtSoDienThoai.setObjectName("txtSoDienThoai")
        self.txtEmail = QtWidgets.QTextEdit(parent=Dialog)
        self.txtEmail.setGeometry(QtCore.QRect(230, 330, 191, 31))
        self.txtEmail.setObjectName("txtEmail")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
#===============================================================================
        #CSS Label
        self.label.setStyleSheet("""color: #FF4500;
                                    font-weight: bold;
                                 """)
        # Thêm hình ảnh Favicon
        pixmap = QPixmap("../Access/Icon/favicon.jpg")
        self.Favicon.setPixmap(pixmap)
        self.Favicon.setScaledContents(True)

        #CSS txt
        self.txtTaiKhoan.setStyleSheet("""
            background-color: white;
            color: black;
        """)
        self.txtMatKhau.setStyleSheet("""
            background-color: white;
            color: black;
        """)
        self.txtEmail.setStyleSheet("""
            background-color: white;
            color: black;
        """)
        self.txtDiaChi.setStyleSheet("""
            background-color: white;
            color: black;
        """)
        self.txtSoDienThoai.setStyleSheet("""
            background-color: white;
            color: black;
        """)
        #Css icon button
        self.btnQuayVe.setIcon(QIcon("../Access/Icon/Quayve.png"))
        self.btnQuayVe.setIconSize(QSize(30,30))
        self.btnSuaNhaCungCap.setIcon(QIcon("../Access/Icon/update.png"))
        self.btnSuaNhaCungCap.setIconSize(QSize(30,30))
        #CSS Button
        self.btnQuayVe.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 20px;
                                    """)
        self.btnSuaNhaCungCap.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 10px;
                                    """)
#===============================================================================
        self.Dialog = Dialog
        self.btnQuayVe.clicked.connect(self.quayve)
        self.btnSuaNhaCungCap.clicked.connect(self.suaNhaCungCap)
#===============================================================================
    def quayve(self):
        from QuanLyNhaCungCap import Ui_Dialog as Ui_Dialog_QuanLyNhaCungCap
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_QuanLyNhaCungCap(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.Dialog.hide()

    def suaNhaCungCap(self):
        from Controller.NhaCungCapController import NhaCungCapController
        idNhaCungCap = self.txtTaiKhoan.toPlainText()
        tenNhaCungCap = self.txtMatKhau.toPlainText()
        diaChi = self.txtDiaChi.toPlainText()
        soDienThoai = self.txtSoDienThoai.toPlainText()
        email = self.txtEmail.toPlainText()
        nhaCungCapController = NhaCungCapController()
        if tenNhaCungCap == "" or diaChi == "" or soDienThoai == "" or email == "":
            QMessageBox.warning(self.Dialog, "Lỗi", "Vui lòng nhập đầy đủ thông tin")
        else:
            nhaCungCapController.updateNhaCungCap(idNhaCungCap, tenNhaCungCap, diaChi, soDienThoai, email)
            QMessageBox.information(self.Dialog, "Thông báo", "Sửa nhà cung cấp thành công")
            self.quayve()

#===============================================================================
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sửa Nhà Cung Cấp"))
        self.iconTaiKhoan.setText(_translate("Dialog", "ID_Nhà Cung_Cấp"))
        self.btnSuaNhaCungCap.setText(_translate("Dialog", "Sửa Nhà Cung Cấp"))
        self.btnQuayVe.setText(_translate("Dialog", "Quay Về"))
        self.iconTaiKhoan_2.setText(_translate("Dialog", "Tên_Nhà Cung_Cấp"))
        self.iconTaiKhoan_3.setText(_translate("Dialog", "Địa_Chỉ"))
        self.iconTaiKhoan_4.setText(_translate("Dialog", "Số_Điện_Thoại"))
        self.iconTaiKhoan_5.setText(_translate("Dialog", "Email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
