# Form implementation generated from reading ui file 'Taodonhang.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controller.DơnHangController import DonhangController


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(774, 429)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(300, 10, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(40, 0, 71, 61))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 771, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btnThemDonhang = QtWidgets.QPushButton(parent=Dialog)
        self.btnThemDonhang.setGeometry(QtCore.QRect(280, 360, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnThemDonhang.setFont(font)
        self.btnThemDonhang.setObjectName("btnThemDonhang")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(650, 360, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnQuayVe.setFont(font)
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.iconTaiKhoan_4 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_4.setGeometry(QtCore.QRect(90, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_4.setFont(font)
        self.iconTaiKhoan_4.setObjectName("iconTaiKhoan_4")
        self.txtIDnhanvien = QtWidgets.QTextEdit(parent=Dialog)
        self.txtIDnhanvien.setGeometry(QtCore.QRect(270, 100, 131, 31))
        self.txtIDnhanvien.setObjectName("txtIDnhanvien")
        self.txtTenkhach = QtWidgets.QTextEdit(parent=Dialog)
        self.txtTenkhach.setGeometry(QtCore.QRect(270, 160, 131, 31))
        self.txtTenkhach.setObjectName("txtTenkhach")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 160, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtSDT = QtWidgets.QTextEdit(parent=Dialog)
        self.txtSDT.setGeometry(QtCore.QRect(270, 220, 131, 31))
        self.txtSDT.setObjectName("txtSDT")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.btnQuayVe.clicked.connect(Dialog.close)
        self.btnThemDonhang.clicked.connect(self.themDonhang)

    def themDonhang(self):
        iduser = self.txtIDnhanvien.toPlainText()
        tenkhach = self.txtTenkhach.toPlainText()
        sdt = self.txtSDT.toPlainText()
        controller = DonhangController()
        controller.addDonHang(iduser, tenkhach, sdt)

    def close(self):
        self.close()



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Thông tin đơn hàng"))
        self.btnThemDonhang.setText(_translate("Dialog", "Thêm"))
        self.btnQuayVe.setText(_translate("Dialog", "Quay Về"))
        self.iconTaiKhoan_4.setText(_translate("Dialog", "ID_Nhân Viên"))
        self.label_3.setText(_translate("Dialog", "Tên khách"))
        self.label_2.setText(_translate("Dialog", "SDT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
