# Form implementation generated from reading ui file 'ThemThongTinNhanVien.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QHeaderView
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from PyQt6.QtGui import QStandardItemModel, QStandardItem
from PyQt6.QtWidgets import QMessageBox

class Ui_Dialog(object):
    def __init__(self, main_window):
        self.main_window = main_window
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(774, 429)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(210, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(40, 0, 71, 61))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 771, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.idSanPham = QtWidgets.QTextEdit(parent=Dialog)
        self.idSanPham.setGeometry(QtCore.QRect(330, 90, 131, 31))
        self.idSanPham.setObjectName("idSanPham")
        self.iconTaiKhoan = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan.setGeometry(QtCore.QRect(160, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan.setFont(font)
        self.iconTaiKhoan.setObjectName("iconTaiKhoan")
        self.btnCapNhatSanPham = QtWidgets.QPushButton(parent=Dialog)
        self.btnCapNhatSanPham.setGeometry(QtCore.QRect(540, 190, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnCapNhatSanPham.setFont(font)
        self.btnCapNhatSanPham.setObjectName("btnCapNhatSanPham")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(660, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnQuayVe.setFont(font)
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.iconTaiKhoan_4 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_4.setGeometry(QtCore.QRect(160, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_4.setFont(font)
        self.iconTaiKhoan_4.setObjectName("iconTaiKhoan_4")
        self.txtNgayNhapKho = QtWidgets.QTextEdit(parent=Dialog)
        self.txtNgayNhapKho.setGeometry(QtCore.QRect(330, 150, 131, 31))
        self.txtNgayNhapKho.setObjectName("txtNgayNhapKho")
        self.iconTaiKhoan_6 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_6.setGeometry(QtCore.QRect(160, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_6.setFont(font)
        self.iconTaiKhoan_6.setObjectName("iconTaiKhoan_6")
        self.txtHanSuDung = QtWidgets.QTextEdit(parent=Dialog)
        self.txtHanSuDung.setGeometry(QtCore.QRect(330, 210, 131, 31))
        self.txtHanSuDung.setObjectName("txtHanSuDung")
        self.iconTaiKhoan_7 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_7.setGeometry(QtCore.QRect(160, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_7.setFont(font)
        self.iconTaiKhoan_7.setObjectName("iconTaiKhoan_7")
        self.txtLoai = QtWidgets.QTextEdit(parent=Dialog)
        self.txtLoai.setGeometry(QtCore.QRect(330, 280, 131, 31))
        self.txtLoai.setObjectName("txtLoai")
        self.txtSoDienThoai = QtWidgets.QTextEdit(parent=Dialog)
        self.txtSoDienThoai.setGeometry(QtCore.QRect(330, 340, 131, 31))
        self.txtSoDienThoai.setObjectName("txtSoDienThoai")
        self.iconTaiKhoan_8 = QtWidgets.QLabel(parent=Dialog)
        self.iconTaiKhoan_8.setGeometry(QtCore.QRect(160, 340, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.iconTaiKhoan_8.setFont(font)
        self.iconTaiKhoan_8.setObjectName("iconTaiKhoan_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        #=================================CSS===========================================
        #CSS Label
        self.label.setStyleSheet("""
                    color: #FF4500;
                    font-weight: bold;
                """)

        #CSS Favicon
        pixamp = QPixmap("../Access/Icon/favicon.jpg")
        self.Favicon.setPixmap(pixamp)
        self.Favicon.setScaledContents(True) \
 \
        #CSS txt
        self.txtLoai.setStyleSheet("""
                                        background-color: white;
                                        color: black;
        """)
        self.txtHanSuDung.setStyleSheet("""
                                        background-color: white;
                                        color: black;
        """)
        self.txtNgayNhapKho.setStyleSheet("""
                                        background-color: white;
                                        color: black;
        """)

        self.idSanPham.setStyleSheet("""
                                        background-color: white;
                                        color: black;
        """)

        self.txtSoDienThoai.setStyleSheet("""
                                        background-color: white;
                                        color: black;
        """)

        #CSS icon button
        self.btnCapNhatSanPham.setIcon(QIcon("../Access/Icon/updateuser.png"))
        self.btnCapNhatSanPham.setIconSize(QSize(40, 40))
        self.btnQuayVe.setIcon(QIcon("../Access/Icon/back.png"))
        self.btnQuayVe.setIconSize(QSize(30 , 30))

        #CSS BUTTON
        self.btnQuayVe.setStyleSheet("""
                                            background-color:#FFFF00;
                                            border-radius: 20px;
                                            border: 2px solid #00FF00;
                                    """)
        #CSS BUTTON
        self.btnCapNhatSanPham.setStyleSheet("""
                                            background-color:#FFFF00;
                                            border-radius: 10px;
                                            border: 2px solid #00FF00;
                                    """)
        #==================================SỰ KIỆN=====================================
        self.Dialog = Dialog
        self.btnQuayVe.clicked.connect(self.quayve)
        self.btnCapNhatSanPham.clicked.connect(self.themThongTinNhanVien)

    #==================================Hàm=========================================
    def quayve(self):
        from ChucNangKhac import Ui_Dialog as Ui_Dialog_ChucNangKhac
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_ChucNangKhac(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.main_window.hide()

    def themThongTinNhanVien(self):
        id = self.idSanPham.toPlainText()
        hoten = self.txtNgayNhapKho.toPlainText()
        tuoi = self.txtHanSuDung.toPlainText()
        diachi = self.txtLoai.toPlainText()
        sdt = self.txtSoDienThoai.toPlainText()
        if id == '' or hoten == '' or tuoi == '' or diachi == '' or sdt == '':
            QMessageBox.warning(self.Dialog, "Lỗi", "Vui lòng nhập đầy đủ thông tin")
        else:
            from Controller.TaiKhoanController import TaiKhoanController
            thongtin = TaiKhoanController()
            thongtin.addThongTinChiTietNhanVien(id, hoten, tuoi, diachi, sdt)
            QMessageBox.information(self.Dialog, "Thông báo", "Thêm thông tin nhân viên thành công")
            self.quayve()







    #===============================================================================
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "THÊM THÔNG TIN NHÂN VIÊN"))
        self.iconTaiKhoan.setText(_translate("Dialog", "ID_User"))
        self.btnCapNhatSanPham.setText(_translate("Dialog", "Thêm "))
        self.btnQuayVe.setText(_translate("Dialog", "Quay Về"))
        self.iconTaiKhoan_4.setText(_translate("Dialog", "Họ_Tên"))
        self.iconTaiKhoan_6.setText(_translate("Dialog", "Tuổi"))
        self.iconTaiKhoan_7.setText(_translate("Dialog", "Địa_Chỉ"))
        self.iconTaiKhoan_8.setText(_translate("Dialog", "Số_Điện_Thoại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
