# Form implementation generated from reading ui file 'ThongKeDoanhThu.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import pandas as pd
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QStandardItem

from Context.DBConnect import Database


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(911, 695)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(310, 10, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.tblDuLieu = QtWidgets.QTableView(parent=Dialog)
        self.tblDuLieu.setGeometry(QtCore.QRect(0, 220, 911, 481))
        self.tblDuLieu.setStyleSheet("background-color:white;\n"
"color:black;")
        self.tblDuLieu.setObjectName("tblDuLieu")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 911, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(850, 0, 61, 51))
        self.btnQuayVe.setStyleSheet("")
        self.btnQuayVe.setText("")
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cbDoanhThu = QtWidgets.QComboBox(parent=Dialog)
        self.cbDoanhThu.setGeometry(QtCore.QRect(190, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.cbDoanhThu.setFont(font)
        self.cbDoanhThu.setObjectName("cbDoanhThu")
        self.cbDoanhThu.addItem("")
        self.cbDoanhThu.addItem("")
        self.cbDoanhThu.addItem("")
        self.btnXuatExcel = QtWidgets.QPushButton(parent=Dialog)
        self.btnXuatExcel.setGeometry(QtCore.QRect(760, 130, 131, 61))
        self.btnXuatExcel.setObjectName("btnXuatExcel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.Dialog = Dialog
        self.btnQuayVe.clicked.connect(self.QuayVe)
        self.load_data()
        self.btnXuatExcel.clicked.connect(self.XuatExcel)


    def QuayVe(self):
        from View.UiManager import Ui_MainWindow
        self.main_window = QtWidgets.QMainWindow()  # tạo một instance mới của QMainWindow
        self.ui = Ui_MainWindow(self.main_window)  # truyền self.main_window như là MainWindow
        self.ui.setupUi(self.main_window)
        self.main_window.show()
        self.Dialog.hide()
    def load_data(self):
        from Controller.DơnHangController import DonhangController
        controller = DonhangController()
        data = controller.getAllChitietdonhang()
        model = QtGui.QStandardItemModel()
        model.setHorizontalHeaderLabels(
            ["ID", "ID Đơn Hàng", "ID Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền", "Ngày bán"])
        for i, nv in enumerate(data):
            for j, data in enumerate(nv):
                model.setItem(i, j, QStandardItem(str(data)))
        self.tblDuLieu.setModel(model)

    def XuatExcel(self):
        try:
            db = Database()
            connection = db.get_connection()
            cursor = connection.cursor()
            cursor.execute("SELECT * FROM chitietdonhang")
            data = cursor.fetchall()

            # Fetching column names dynamically from the cursor
            columns = [desc[0] for desc in cursor.description]

            df = pd.DataFrame(data, columns=columns)

            excel_file = 'demo.xlsx'
            df.to_excel(excel_file, index=False, engine='xlsxwriter')
            print("Export successful.")
        except Exception as e:
            print(f"An error occurred: {e}")
        finally:
            cursor.close()
            connection.close()



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Thống Kê Doanh Thu"))
        self.label_2.setText(_translate("Dialog", "Doanh Thu Theo:"))
        self.cbDoanhThu.setItemText(0, _translate("Dialog", "Tuần"))
        self.cbDoanhThu.setItemText(1, _translate("Dialog", "Tháng"))
        self.cbDoanhThu.setItemText(2, _translate("Dialog", "Năm"))
        self.btnXuatExcel.setText(_translate("Dialog", "Xuất Ra EXCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
