# Form implementation generated from reading ui file 'ThongKeDoanhThu.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon


class Ui_Dialog(object):
    def __init__(self, main_window):
      self.main_window = main_window
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(911, 695)
        Dialog.setStyleSheet("background-color: #D0F9FD;")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(310, 10, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.tblDuLieu = QtWidgets.QTableView(parent=Dialog)
        self.tblDuLieu.setGeometry(QtCore.QRect(0, 220, 911, 481))
        self.tblDuLieu.setStyleSheet("background-color:white;\n"
"color:black;")
        self.tblDuLieu.setObjectName("tblDuLieu")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(0, 80, 911, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btnQuayVe = QtWidgets.QPushButton(parent=Dialog)
        self.btnQuayVe.setGeometry(QtCore.QRect(850, 0, 61, 51))
        self.btnQuayVe.setStyleSheet("")
        self.btnQuayVe.setText("")
        self.btnQuayVe.setObjectName("btnQuayVe")
        self.Favicon = QtWidgets.QLabel(parent=Dialog)
        self.Favicon.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cbDoanhThu = QtWidgets.QComboBox(parent=Dialog)
        self.cbDoanhThu.setGeometry(QtCore.QRect(190, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.cbDoanhThu.setFont(font)
        self.cbDoanhThu.setObjectName("cbDoanhThu")
        self.cbDoanhThu.addItem("")
        self.cbDoanhThu.addItem("")
        self.cbDoanhThu.addItem("")
        self.btnXuatExcel = QtWidgets.QPushButton(parent=Dialog)
        self.btnXuatExcel.setGeometry(QtCore.QRect(760, 130, 131, 61))
        self.btnXuatExcel.setObjectName("btnXuatExcel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        #=============================CSS============================================
        #
        #CSS thêm Favicon
        pixamp = QPixmap("../Access/Icon/favicon.jpg")
        self.Favicon.setPixmap(pixamp)
        self.Favicon.setScaledContents(True)

        #CSS Label
        self.label.setStyleSheet("""
                    color: #FF4500;
                    font-weight: bold;
                """)

        #CSS icon
        self.btnXuatExcel.setIcon(QIcon("../Access/Icon/excel.png"))
        self.btnXuatExcel.setIconSize(QSize(40, 40))
        self.btnQuayVe.setIcon(QIcon("../Access/Icon/back.png"))
        self.btnQuayVe.setIconSize(QSize(40, 40))

        #CSS button
        self.btnXuatExcel.setStyleSheet("""
                                              background-color:#FFFF00;
                                              border-radius: 10px;
                                              border: 2px solid blue;
                                        """)
        self.btnQuayVe.setStyleSheet("""      
                                              background-color:#FFFF00;
                                              border-radius: 10px;
                                    """)

        #CSS combobox
        self.cbDoanhThu.setStyleSheet("""
            background: white;
            border: 2px solid black;
            border-radius: 10px;
        """)
#=================================SỰ KIỆN=====================================
        self.Dialog = Dialog
        self.btnQuayVe.clicked.connect(self.QuayVe)

#=================================HÀM========================================
    def QuayVe(self):
      from UiAdmin import Ui_MainWindow
      self.main_window = QtWidgets.QMainWindow()  # tạo một instance mới của QMainWindow
      self.ui = Ui_MainWindow(self.main_window)  # truyền self.main_window như là MainWindow
      self.ui.setupUi(self.main_window)
      self.main_window.show()
      self.Dialog.hide()



    #=========================================================================
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Thống Kê Doanh Thu"))
        self.label_2.setText(_translate("Dialog", "Doanh Thu Theo:"))
        self.cbDoanhThu.setItemText(0, _translate("Dialog", "Tuần"))
        self.cbDoanhThu.setItemText(1, _translate("Dialog", "Tháng"))
        self.cbDoanhThu.setItemText(2, _translate("Dialog", "Năm"))
        self.btnXuatExcel.setText(_translate("Dialog", "Xuất Ra EXCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
