# Form implementation generated from reading ui file '.\UiManager.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from QuanLyNhaCungCap import Ui_Dialog as Ui_Dialog_NhaCungCap
from QuanLySanPham import Ui_Dialog as Ui_Dialog_SanPham
from ThongKeDoanhThu import Ui_Dialog as Ui_Dialog_ThongKe
from QuanLyDonHang import Ui_Dialog as Ui_Dialog_DonHang

class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        self.MainWindow = MainWindow
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1257, 889)
        MainWindow.setStyleSheet("background-color: #D0F9FD;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1271, 111))
        self.widget.setObjectName("widget")
        self.Favicon = QtWidgets.QLabel(parent=self.widget)
        self.Favicon.setGeometry(QtCore.QRect(80, 0, 131, 91))
        self.Favicon.setText("")
        self.Favicon.setObjectName("Favicon")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(420, 10, 501, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=self.widget)
        self.line.setGeometry(QtCore.QRect(0, 100, 1261, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 110, 231, 801))
        self.widget_2.setObjectName("widget_2")
        self.btnDangXuat = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnDangXuat.setGeometry(QtCore.QRect(0, 670, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btnDangXuat.setFont(font)
        self.btnDangXuat.setObjectName("btnDangXuat")
        self.btnSanPham = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnSanPham.setGeometry(QtCore.QRect(0, 10, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btnSanPham.setFont(font)
        self.btnSanPham.setObjectName("btnSanPham")
        self.btnThongKe = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnThongKe.setGeometry(QtCore.QRect(0, 140, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btnThongKe.setFont(font)
        self.btnThongKe.setObjectName("btnThongKe")
        self.line_10 = QtWidgets.QFrame(parent=self.widget_2)
        self.line_10.setGeometry(QtCore.QRect(0, 110, 231, 16))
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_12 = QtWidgets.QFrame(parent=self.widget_2)
        self.line_12.setGeometry(QtCore.QRect(0, 250, 231, 16))
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_12.setObjectName("line_12")
        self.btnDonHang = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnDonHang.setGeometry(QtCore.QRect(0, 280, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btnDonHang.setFont(font)
        self.btnDonHang.setObjectName("btnDonHang")
        self.btnNhaCungCap = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnNhaCungCap.setGeometry(QtCore.QRect(0, 410, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btnNhaCungCap.setFont(font)
        self.btnNhaCungCap.setObjectName("btnNhaCungCap")
        self.line_13 = QtWidgets.QFrame(parent=self.widget_2)
        self.line_13.setGeometry(QtCore.QRect(0, 380, 231, 16))
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(parent=self.widget_2)
        self.line_14.setGeometry(QtCore.QRect(0, 510, 231, 16))
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(220, 110, 31, 801))
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.Images = QtWidgets.QLabel(parent=self.centralwidget)
        self.Images.setGeometry(QtCore.QRect(240, 110, 1021, 801))
        self.Images.setText("")
        self.Images.setObjectName("Images")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #================================CSS===========================================

        #Css Label
        self.label.setStyleSheet("""
                    color: #FF4500;
                    font-weight: bold;
                """)

        # Thêm hình ảnh vào giao diện
        pixamp = QPixmap("../Access/Icon/favicon.jpg")
        self.Favicon.setPixmap(pixamp)
        self.Favicon.setScaledContents(True)

        pixamp = QPixmap("../Access/Images/CoHaiLua.png")
        self.Images.setPixmap(pixamp)
        self.Images.setScaledContents(True)

        #Thêm Icon cho button


        self.btnThongKe.setIcon(QIcon("../Access/Icon/statistical.png"))
        self.btnThongKe.setIconSize(QSize(40, 40))
        self.btnSanPham.setIcon(QIcon("../Access/Icon/vegetables.png"))
        self.btnSanPham.setIconSize(QSize(40, 40))
        self.btnDangXuat.setIcon(QIcon("../Access/Icon/log-out.png"))
        self.btnDangXuat.setIconSize(QSize(40, 40))
        self.btnDonHang.setIcon(QIcon("../Access/Icon/oder.png"))
        self.btnDonHang.setIconSize(QSize(40, 40))
        self.btnNhaCungCap.setIcon(QIcon("../Access/Icon/NhaCungCap.png"))
        self.btnNhaCungCap.setIconSize(QSize(40, 40))


        #CSS Button
        self.btnDonHang.setStyleSheet("""
                                        background-color:#FFFF00;
                                        border-radius: 10px;
                                        border: 2px solid #00FF00;
                                       """)
        self.btnNhaCungCap.setStyleSheet("""
                                        background-color:#FFFF00;
                                        border-radius: 10px;
                                        border: 2px solid #00FF00;
                                     """)
        self.btnSanPham.setStyleSheet("""
                                        background-color:#FFFF00;
                                        border-radius: 10px;
                                        border: 2px solid #00FF00;
                                      """)
        self.btnDangXuat.setStyleSheet("""
                                        background-color:#FFFF00;
                                        border-radius: 10px;
                                        border: 2px solid #00FF00;
                                      """)
        self.btnThongKe.setStyleSheet("""
                                        background-color:#FFFF00;
                                        border-radius: 10px;
                                        border: 2px solid #00FF00;
                                      """)



    #=================================Sự Kiện=====================================
        self.btnDangXuat.clicked.connect(self.openLogin)
        self.btnSanPham.clicked.connect(self.openSanPham)
        self.btnThongKe.clicked.connect(self.openThongKe)
        self.btnDonHang.clicked.connect(self.openDonHang)
        self.btnNhaCungCap.clicked.connect(self.openNhaCungCap)

#===============================================================================
    def openLogin(self):
        from Login import Ui_Dialog as Ui_Dialog_Login
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_Login(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.hide()
    def openSanPham(self):
        from QuanLySanPhamManager import Ui_Dialog as Ui_Dialog_SanPham
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_SanPham(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.hide()
    def openThongKe(self):
        from ThongKeDoanhThuManager import Ui_Dialog as Ui_Dialog_ThongKe
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_ThongKe()
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.hide()
    def openDonHang(self):
        from Quanlydonhangmanager import Ui_Dialog as Ui_Dialog_DonHang
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_DonHang(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.hide()
    def openNhaCungCap(self):
        from QuanLyNhaCungCapManager import Ui_Dialog as Ui_Dialog_NhaCungCap
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog_NhaCungCap(self.window)
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.hide()



    #==============================================================================
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cửa Hàng Nông Sản __ Cô Hai Lúa"))
        self.btnDangXuat.setText(_translate("MainWindow", "Đăng xuất"))
        self.btnSanPham.setText(_translate("MainWindow", "Sản Phẩm"))
        self.btnThongKe.setText(_translate("MainWindow", "Thống Kê"))
        self.btnDonHang.setText(_translate("MainWindow", "Đơn Hàng"))
        self.btnNhaCungCap.setText(_translate("MainWindow", "Nhà Cung Cấp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
